-- KamsoraAPM relational metadata - API functions.
-- Insert  -> fn_api_post_<table>     returns text (newly generated UUID)
-- Select  -> fn_api_select_<entity>  returns SETOF refcursor over json_agg

-- ---------------------------------------------------------------------------
-- mastertenants
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_api_post_mastertenants(
    _tenant_name           text,
    _tenant_slug           text,
    _plan_type             text,
    _data_retention_days   int,
    _max_spans_per_minute  int,
    _contact_email         text,
    _postedby              text)
    RETURNS text
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    _sysTenantUuid text;
BEGIN
    INSERT INTO public.mastertenants(
        tenant_name, tenant_slug, plan_type, data_retention_days,
        max_spans_per_minute, contact_email, posteddatetime, postedby
    )
    SELECT
        _tenant_name, _tenant_slug, COALESCE(_plan_type, 'free'),
        COALESCE(_data_retention_days, 14),
        COALESCE(_max_spans_per_minute, 10000),
        _contact_email, CURRENT_TIMESTAMP, _postedby
    RETURNING systenantuuid INTO _sysTenantUuid;

    RETURN _sysTenantUuid;
END;
$BODY$;

CREATE OR REPLACE FUNCTION public.fn_api_select_mastertenants()
    RETURNS SETOF refcursor
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
    _transData refcursor;
BEGIN
    OPEN _transData FOR
        SELECT json_agg(row_to_json(tbl.*)) AS transData
        FROM (
            SELECT tenantid, systenantuuid, tenant_name, tenant_slug, plan_type,
                   data_retention_days, max_spans_per_minute, max_metrics_per_minute,
                   max_logs_per_minute, status, contact_email,
                   posteddatetime, postedby, updatedby, updateddatetime
            FROM public.mastertenants
            WHERE status <> 'deleted'
            ORDER BY tenantid DESC
        ) tbl;
    RETURN NEXT _transData;
END;
$BODY$;

-- ---------------------------------------------------------------------------
-- masterapi_keys
-- _key_hash is the bcrypt hash of the cleartext API key. The cleartext is
-- generated by the Dashboard.Api at issue time and is NOT persisted server-side.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_api_post_masterapi_keys(
    _systenantuuid   text,
    _key_name        text,
    _key_prefix      text,
    _key_hash        text,
    _scopes          text,
    _expires_at      timestamp,
    _postedby        text)
    RETURNS text
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    _sysApiKeyUuid text;
BEGIN
    INSERT INTO public.masterapi_keys(
        systenantuuid, key_name, key_prefix, key_hash, scopes,
        expires_at, posteddatetime, postedby
    )
    SELECT
        _systenantuuid, _key_name, _key_prefix, _key_hash,
        COALESCE(_scopes, 'ingest'), _expires_at,
        CURRENT_TIMESTAMP, _postedby
    RETURNING sysapikeyuuid INTO _sysApiKeyUuid;

    RETURN _sysApiKeyUuid;
END;
$BODY$;

CREATE OR REPLACE FUNCTION public.fn_api_select_masterapi_keys(_systenantuuid text)
    RETURNS SETOF refcursor
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
    _transData refcursor;
BEGIN
    OPEN _transData FOR
        SELECT json_agg(row_to_json(tbl.*)) AS transData
        FROM (
            SELECT apikeyid, sysapikeyuuid, systenantuuid, key_name, key_prefix,
                   scopes, expires_at, revoked_at, last_used_at,
                   posteddatetime, postedby, updatedby, updateddatetime
            FROM public.masterapi_keys
            WHERE systenantuuid = _systenantuuid
              AND revoked_at IS NULL
            ORDER BY apikeyid DESC
        ) tbl;
    RETURN NEXT _transData;
END;
$BODY$;

-- ---------------------------------------------------------------------------
-- tblapm_service_registry
-- Upsert-style helper: invoked on every Agent Ping. Idempotent.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_api_post_tblapm_service_registry(
    _systenantuuid     text,
    _service_name      text,
    _service_namespace text,
    _sdk_language      text,
    _sdk_version       text,
    _runtime_version   text,
    _postedby          text)
    RETURNS text
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    _sysServiceTransId text;
BEGIN
    INSERT INTO public.tblapm_service_registry(
        systenantuuid, service_name, service_namespace,
        sdk_language, sdk_version, runtime_version,
        first_seen_at, last_seen_at, posteddatetime, postedby
    )
    SELECT
        _systenantuuid, _service_name, _service_namespace,
        COALESCE(_sdk_language, 'dotnet'), _sdk_version, _runtime_version,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, _postedby
    ON CONFLICT (systenantuuid, service_name) DO UPDATE
       SET sdk_version      = EXCLUDED.sdk_version,
           runtime_version  = EXCLUDED.runtime_version,
           last_seen_at     = CURRENT_TIMESTAMP,
           updatedby        = _postedby,
           updateddatetime  = CURRENT_TIMESTAMP
    RETURNING sysservicetransid INTO _sysServiceTransId;

    RETURN _sysServiceTransId;
END;
$BODY$;

CREATE OR REPLACE FUNCTION public.fn_api_select_tblapm_service_registry(_systenantuuid text)
    RETURNS SETOF refcursor
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
    _transData refcursor;
BEGIN
    OPEN _transData FOR
        SELECT json_agg(row_to_json(tbl.*)) AS transData
        FROM (
            SELECT serviceid, sysservicetransid, systenantuuid, service_name,
                   service_namespace, sdk_language, sdk_version, runtime_version,
                   first_seen_at, last_seen_at,
                   posteddatetime, postedby, updatedby, updateddatetime
            FROM public.tblapm_service_registry
            WHERE systenantuuid = _systenantuuid
            ORDER BY last_seen_at DESC
        ) tbl;
    RETURN NEXT _transData;
END;
$BODY$;

-- ---------------------------------------------------------------------------
-- tblapm_alert_rules
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_api_post_tblapm_alert_rules(
    _systenantuuid    text,
    _rule_name        text,
    _description      text,
    _signal_type      text,
    _service_filter   text,
    _operator         text,
    _threshold        double precision,
    _window_seconds   int,
    _for_seconds      int,
    _severity         text,
    _channel_uuids    text[],
    _postedby         text)
    RETURNS text
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    _sysRuleTransId text;
BEGIN
    INSERT INTO public.tblapm_alert_rules(
        systenantuuid, rule_name, description, signal_type, service_filter,
        operator, threshold, window_seconds, for_seconds, severity,
        channel_uuids, posteddatetime, postedby
    )
    SELECT
        _systenantuuid, _rule_name, _description, _signal_type, _service_filter,
        _operator, _threshold,
        COALESCE(_window_seconds, 60),
        COALESCE(_for_seconds, 120),
        COALESCE(_severity, 'warning'),
        COALESCE(_channel_uuids, '{}'::text[]),
        CURRENT_TIMESTAMP, _postedby
    RETURNING sysruletransid INTO _sysRuleTransId;

    RETURN _sysRuleTransId;
END;
$BODY$;

CREATE OR REPLACE FUNCTION public.fn_api_select_tblapm_alert_rules(_systenantuuid text)
    RETURNS SETOF refcursor
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000
AS $BODY$
DECLARE
    _transData refcursor;
BEGIN
    OPEN _transData FOR
        SELECT json_agg(row_to_json(tbl.*)) AS transData
        FROM (
            SELECT ruleid, sysruletransid, systenantuuid, rule_name, description,
                   enabled, signal_type, service_filter, operator, threshold,
                   window_seconds, for_seconds, severity, channel_uuids,
                   last_evaluated_at, last_state,
                   posteddatetime, postedby, updatedby, updateddatetime
            FROM public.tblapm_alert_rules
            WHERE systenantuuid = _systenantuuid
            ORDER BY ruleid DESC
        ) tbl;
    RETURN NEXT _transData;
END;
$BODY$;
