#requires -version 5
<#
.SYNOPSIS
  Generate deploy/docker/.env with secure random secrets for the KamsoraAPM stack.

.DESCRIPTION
  KamsoraAPM refuses to start in the Production environment while any secret is
  still a repository default (see DevSecretsGuard). This script writes a .env
  with freshly generated, cryptographically random database passwords and a JWT
  signing key, plus a random first-run admin password, so a clean clone can
  bring the stack up in one shot. Re-run with -Force to regenerate (the previous
  .env is backed up to .env.bak).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/init-env.ps1
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/init-env.ps1 -AdminEmail you@company.com -Force
#>
[CmdletBinding()]
param(
    [switch]$Force,
    [string]$AdminEmail = "admin@example.com",
    [string]$EnvFile
)

$ErrorActionPreference = "Stop"

# Resolve deploy/docker/.env relative to this script unless an explicit path is given.
if (-not $EnvFile) {
    $repoRoot = Split-Path -Parent $PSScriptRoot
    $EnvFile  = Join-Path $repoRoot "deploy/docker/.env"
}

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host "$EnvFile already exists. Re-run with -Force to regenerate (a .bak is kept)." -ForegroundColor Yellow
    exit 1
}

# Cryptographically random alphanumeric (safe for connection strings and .env).
function New-AlphaNum([int]$Length) {
    $chars = [char[]]('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')
    $bytes = New-Object byte[] $Length
    ([System.Security.Cryptography.RandomNumberGenerator]::Create()).GetBytes($bytes)
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}

function New-Base64Key([int]$Bytes) {
    $b = New-Object byte[] $Bytes
    ([System.Security.Cryptography.RandomNumberGenerator]::Create()).GetBytes($b)
    [Convert]::ToBase64String($b)
}

$pgPass    = New-AlphaNum 32
$chPass    = New-AlphaNum 32
$jwtKey    = New-Base64Key 48
$adminPass = New-AlphaNum 20

if (Test-Path $EnvFile) {
    # Clear a read-only attribute so the write below does not fail with "Access is denied".
    try { (Get-Item $EnvFile -Force).Attributes = [System.IO.FileAttributes]::Normal } catch {}
    try {
        Copy-Item $EnvFile "$EnvFile.bak" -Force
        Write-Host "Backed up existing .env to $EnvFile.bak"
    } catch {
        Write-Host "Could not back up the existing .env (continuing anyway): $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

$content = @"
# Generated by scripts/init-env.ps1 - DO NOT commit this file.
# Every secret below is a freshly generated random value.

KAMSORA_APM_VERSION=edge

POSTGRES_PASSWORD=$pgPass
CLICKHOUSE_PASSWORD=$chPass

KAMSORA_APM_JWT_SIGNING_KEY=$jwtKey

SEED_ADMIN_EMAIL=$AdminEmail
SEED_ADMIN_PASSWORD=$adminPass

SEED_TENANT_NAME=My Company
SEED_TENANT_SLUG=my-company
"@

# ASCII (no BOM) - a UTF-8 BOM on line 1 breaks docker compose env parsing.
try {
    [System.IO.File]::WriteAllText($EnvFile, $content, (New-Object System.Text.ASCIIEncoding))
} catch {
    Write-Host ""
    Write-Host "ERROR: could not write $EnvFile" -ForegroundColor Red
    Write-Host "Reason: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host ""
    Write-Host "Fixes to try:" -ForegroundColor Yellow
    Write-Host "  1. Close any editor that has deploy/docker/.env open, then rerun."
    Write-Host "  2. Run this shell as Administrator (right-click PowerShell > Run as administrator), then rerun."
    Write-Host "  3. Or move the repo under your user folder, e.g. C:\Users\$env:USERNAME\KamsoraAPM, and rerun there."
    exit 1
}

Write-Host ""
Write-Host "Wrote $EnvFile with fresh random secrets." -ForegroundColor Green
Write-Host ""
Write-Host "Dashboard login once the stack is up (http://localhost:3000):"
Write-Host "  email:    $AdminEmail"
Write-Host "  password: $adminPass"
Write-Host ""
Write-Host "Next:"
Write-Host "  docker compose -f deploy/docker/docker-compose.yml --env-file deploy/docker/.env --profile apps up -d --build"
