#!/usr/bin/env bash
#
# Generate deploy/docker/.env with secure random secrets for the KamsoraAPM stack.
#
# KamsoraAPM refuses to start in the Production environment while any secret is
# still a repository default (see DevSecretsGuard). This writes a .env with
# freshly generated random database passwords and a JWT signing key, plus a
# random first-run admin password, so a clean clone can bring the stack up in
# one shot. Re-run with --force to regenerate (the previous .env is backed up).
#
#   ./scripts/init-env.sh
#   ./scripts/init-env.sh --force
#
# Note: NOT set -o pipefail on purpose - `tr | head` makes tr die with SIGPIPE,
# which would otherwise abort the script.
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_ROOT/deploy/docker/.env"
ADMIN_EMAIL="admin@example.com"

FORCE="no"
[ "${1:-}" = "--force" ] && FORCE="yes"

if [ -f "$ENV_FILE" ] && [ "$FORCE" != "yes" ]; then
  echo "deploy/docker/.env already exists. Re-run with --force to regenerate (a .bak is kept)." >&2
  exit 1
fi

# Cryptographically random alphanumeric (safe for connection strings and .env).
rand_alnum() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"; }

PG_PASS="$(rand_alnum 32)"
CH_PASS="$(rand_alnum 32)"
JWT_KEY="$(openssl rand -base64 48 2>/dev/null || head -c 48 /dev/urandom | base64 | tr -d '\n')"
ADMIN_PASS="$(rand_alnum 20)"

if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.bak"
  echo "Backed up existing .env to $ENV_FILE.bak"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-env.sh - DO NOT commit this file.
# Every secret below is a freshly generated random value.

KAMSORA_APM_VERSION=edge

POSTGRES_PASSWORD=$PG_PASS
CLICKHOUSE_PASSWORD=$CH_PASS

KAMSORA_APM_JWT_SIGNING_KEY=$JWT_KEY

SEED_ADMIN_EMAIL=$ADMIN_EMAIL
SEED_ADMIN_PASSWORD=$ADMIN_PASS

SEED_TENANT_NAME=My Company
SEED_TENANT_SLUG=my-company
EOF

echo ""
echo "Wrote $ENV_FILE with fresh random secrets."
echo "Dashboard login once the stack is up (http://localhost:3000):"
echo "  email:    $ADMIN_EMAIL"
echo "  password: $ADMIN_PASS"
echo ""
echo "Next:"
echo "  docker compose -f deploy/docker/docker-compose.yml --env-file deploy/docker/.env --profile apps up -d --build"
